# src/Resources/config/services.yaml (dans ton bundle)
services:
  Davidannebicque\HtmlToSpreadsheetBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,Tests}'
    autowire: true
    autoconfigure: true
